// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: user_mapping.proto
// script: protoc -I=./protobuf/proto --go_out=./ ./protobuf/proto/user_mapping.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMappingDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectKey   string            `protobuf:"bytes,1,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
	SendTime     int64             `protobuf:"varint,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Identifies   map[string]string `protobuf:"bytes,3,rep,name=identifies,proto3" json:"identifies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DataSourceId string            `protobuf:"bytes,4,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
}

func (x *UserMappingDto) Reset() {
	*x = UserMappingDto{}
	mi := &file_user_mapping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMappingDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMappingDto) ProtoMessage() {}

func (x *UserMappingDto) ProtoReflect() protoreflect.Message {
	mi := &file_user_mapping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMappingDto.ProtoReflect.Descriptor instead.
func (*UserMappingDto) Descriptor() ([]byte, []int) {
	return file_user_mapping_proto_rawDescGZIP(), []int{0}
}

func (x *UserMappingDto) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *UserMappingDto) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *UserMappingDto) GetIdentifies() map[string]string {
	if x != nil {
		return x.Identifies
	}
	return nil
}

func (x *UserMappingDto) GetDataSourceId() string {
	if x != nil {
		return x.DataSourceId
	}
	return ""
}

type UserMappingDtoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*UserMappingDto `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *UserMappingDtoList) Reset() {
	*x = UserMappingDtoList{}
	mi := &file_user_mapping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMappingDtoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMappingDtoList) ProtoMessage() {}

func (x *UserMappingDtoList) ProtoReflect() protoreflect.Message {
	mi := &file_user_mapping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMappingDtoList.ProtoReflect.Descriptor instead.
func (*UserMappingDtoList) Descriptor() ([]byte, []int) {
	return file_user_mapping_proto_rawDescGZIP(), []int{1}
}

func (x *UserMappingDtoList) GetValues() []*UserMappingDto {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_user_mapping_proto protoreflect.FileDescriptor

var file_user_mapping_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x44, 0x74, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x44, 0x74, 0x6f, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x64, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x3d, 0x0a, 0x0f,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3d, 0x0a, 0x12, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x44, 0x74, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x44,
	0x74, 0x6f, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_mapping_proto_rawDescOnce sync.Once
	file_user_mapping_proto_rawDescData = file_user_mapping_proto_rawDesc
)

func file_user_mapping_proto_rawDescGZIP() []byte {
	file_user_mapping_proto_rawDescOnce.Do(func() {
		file_user_mapping_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_mapping_proto_rawDescData)
	})
	return file_user_mapping_proto_rawDescData
}

var file_user_mapping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_mapping_proto_goTypes = []any{
	(*UserMappingDto)(nil),     // 0: UserMappingDto
	(*UserMappingDtoList)(nil), // 1: UserMappingDtoList
	nil,                        // 2: UserMappingDto.IdentifiesEntry
}
var file_user_mapping_proto_depIdxs = []int32{
	2, // 0: UserMappingDto.identifies:type_name -> UserMappingDto.IdentifiesEntry
	0, // 1: UserMappingDtoList.values:type_name -> UserMappingDto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_mapping_proto_init() }
func file_user_mapping_proto_init() {
	if File_user_mapping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_mapping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_mapping_proto_goTypes,
		DependencyIndexes: file_user_mapping_proto_depIdxs,
		MessageInfos:      file_user_mapping_proto_msgTypes,
	}.Build()
	File_user_mapping_proto = out.File
	file_user_mapping_proto_rawDesc = nil
	file_user_mapping_proto_goTypes = nil
	file_user_mapping_proto_depIdxs = nil
}
