name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Module tidy
        run: go mod tidy

      - name: Publish to proxy
        env:
          GOPROXY: proxy.golang.org
        run: |
          # 确保所有依赖项都正确安装
          go list -m all
          
          # 使用 go list 命令请求版本的代理缓存，以便 proxy.golang.org 缓存新版本
          go list -m github.com/growingio/growingio-sdk-go@${GITHUB_REF#refs/tags/}
          
          echo "Published to proxy.golang.org"

      - name: Confirm the module is available on proxy.golang.org
        run: |
          curl -sL https://proxy.golang.org/github.com/growingio/growingio-sdk-go/@v/${GITHUB_REF#refs/tags/}.info
